apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v1qknoy2d-nodejs 
  janus-idp.io/tekton: v1qknoy2d-nodejs
  backstage.io/kubernetes-id: v1qknoy2d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v1qknoy2d-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml